# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog 
import cv2
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 481, 471))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("hello.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_button.setGeometry(QtCore.QRect(10, 10, 89, 25))
        self.browse_button.setObjectName("browse_button")
        self.browse_button.clicked.connect(self.clicked_browse)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 80, 86, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(120, 80, 89, 25))
        self.submit_button.setObjectName("submit_button")
        self.submit_button.clicked.connect(self.clicked_submit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browse_button.setText(_translate("MainWindow", "Open Image"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Item1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Item2"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))

    def clicked_browse(self):
        # print('clicked')
        self.fname = QFileDialog.getOpenFileName(MainWindow, "opne file", "", "All Files (*) ;; Image File (*.jpg) ;;")
        print(self.fname[0])
        self.image = cv2.imread(self.fname[0])
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(self.fname[0]))
        self.label.setScaledContents(True)
        self.comboBox.clear()
        for i in range(random.randint(2,10)):
            self.comboBox.addItem(f"hello{i}")

    def clicked_submit(self):
        current_selection = self.comboBox.currentText()
        self.rotated_image = cv2.rotate(self.image, cv2.ROTATE_180)
        self.rotated_image = cv2.putText(self.rotated_image, str(current_selection), (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,0,0), 3, cv2.LINE_AA)
        cv2.imwrite("temp.jpg",self.rotated_image)
        self.label.setPixmap(QtGui.QPixmap("temp.jpg"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
